from dotenv import load_dotenv
from openai import OpenAI
import os

# Setup for OpenAI
load_dotenv()
api_key = os.getenv("OPENAI_API_KEY")
client = OpenAI(api_key=api_key)

# Prompt OpenAi
completion = client.chat.completions.create(
    model="gpt-3.5-turbo",
    messages=[
        {"role": "system",
        "content": "Given the scraped data from Amazon, describe what materials that the product is made out of and approximately the amount of that material. Describe the environmental impacts of said material taking in consideration how much of it is present in the product. Also describe the envirenmental impact of shipping the product from its manufactured location. Also, output a response in a organized under the headers of: 'Materials', 'Manufacturing', 'Shipping'"
        },
        {"role": "user", 
        #  "content": """{'productTitle': 'Neineiwu Women Dressy Casual V-Neck T-Shirts Loose Puff Short-Sleeve Tops Tunic Blouse', 'productFactsDesktopExpander': 'Product detailsFabric type95% Rayon, 5% Spandex, Soft and Stretchable FabricCare instructionsMachine Wash or Hand WashOriginImportedClosure typePull OnCountry of OriginChinaAbout this itemSkin-Friendly Material. Women dressy casual short-sleeve blouse is soft, Lightweight, fit loose, not tight and falls nicely.Features: Classic V-neck and puff sleeve design, The short puff sleeve is feminine and cute. Good coverage on the upper arm. Great longer length to cover the the butt. A nicer dressy t-shirt.Matching: V-neck women t-shirts nice for dressing up or down,the V is perfect for stacking necklaces. Just long enough to wear with leggings and flattering either casual or dressy. You can also pair it with casual skirts, jeans, shorts, boots, cardigans, jacket, coat etc.Occasion: Puff short-sleeve tops for women is greats for work, beach, office, travel, holiday, picnic, vacation, party, club and dating. Fashion T-Shirts Tops Tunic Blouse for women fashion 2023. Suit for summer, spring and fall.Size&Garment Care: US SIZE: S=(US 4-6), M=(US 8-10), L=(US 12-14), XL=(US 16-18), 2XL=(US 18-20). Machine or Hand Wash with cold water. Do not tumble dry.See moreAbout this item', 'important-information': 'Important informationTo report an issue with this product or seller,click here.', 'aplus': "From the brandWelcome to Neineiwu!!!You can find some Casual&Dressy tops and blouses for women fashion in here! Neineiwu can provide options for your everyday wardrobe.Previous pageWomens Wops Dressy CasualVisit the StoreBlouses & Button-down shirtsVisit the StoreHow did we get our start?Neineiwu was founded in 2018, a company that specializes in the design and production of women's fashion.What makes our products unique?Neineiwu always try to provide new trendy and high quality womens tops. We are eager to design popular and unique clothing. We are committed to provide best shopping experience to our customers.What problem are we solving?Let women show their beauty through different clothesLet women have more choice and style display in dressing,The purpose is to make women more attractive and enjoy life better.Next page"} """
         "content": """{'productTitle': 'FIJI Natural Artesian Bottled Water 500 mL / 16.9 Fl Ounce (Pack of 24)', 'feature-bullets': 'About this itemPack size: Pack of 24, 500mL (16.9 Fl Oz) bottles of FIJI WaterEveryday hydration: Our most popular item, the 500mL bottle, is the perfect grab-and-go size. Does Not Contain Any of the 8 Major AllergensDouble Electrolytes: FIJI Water has more than double the electrolytes as the top 
premium bottled water brands for a soft, smooth taste. And while theirs are added, ours occur naturally from slowly filtering through volcanic rockNatural artesian: Bottled from a natural, sustainable artesian aquifer in the remote Fijian Islands, untouched by manSoft, smooth taste: Rain slowly filters through volcanic rock, giving FIJI Water a perfectly balanced 7.7 pH, and its signature, soft smooth tasteOur 550mL bottles are made from 100% recycled plastic, bottle only.', 'productDescription': 'Product DescriptionCase includes 24, 500mL (16.9oz) bottles of FIJI Water. The 500mL size is perfect for everyday on-the-go hydration. Its soft, smooth taste comes from its extraordinary source -- a protected artesian aquifer found deep underground in the remote Fiji Islands. FIJI Water is the choice of discerning top chefs, fine restaurants and hotels around the world.About Brand :Our most popular item, the 500 mL bottle, is the perfect grab-and-go size.', 'important-information': 'Important informationSafety InformationThis product is labelled to United States standards and may differ from similar products sold elsewhere in its ingredients, labeling and allergen warningsIngredientsWaterLegal DisclaimerStatements regarding dietary supplements have not been evaluated by the FDA and are not intended to diagnose, treat, cure, or prevent any disease or health condition.To report an issue with this product or seller,click 
here.', 'aplus': "From the manufacturerFeaturesFrom CloudEarth’s Finest Water starts in the clouds. High above Fiji, over 1,600 miles from the nearest continent, tropical rainfall is purified by equatorial trade winds.Through RockThe rainwater slowly filters through volcanic rock, gathering electrolytes and minerals, contributing to the distinctly soft, smooth taste of FijI Water.To BottleThen the water collects in a natural artesian aquifer deep below the Earth’s surface before it’s bottled at the source. Untouched by man, until you unscrew the cap.Fit For Every OccasionWhether hosting a party, replenishing after a workout, or hydrating on-the-go, FijI Water has the perfect bottle size to fit your every need.330mL Bottle500mL Bottle700mL Bottle1L Bottle1.5L BottleFrom Fiji✓✓✓✓✓Natural Electrolytes/Minerals✓✓✓✓✓ActivityGroup events, Dinner parties, Kids' activitiesOn-the-go activities, Everyday hydration, Office environmentsExercise and fitness, Everyday hydration, TravelAll-day hydration, Camping/Hiking, TravelAll-day hydration, Camping/Hiking, Traveloz.11.15 oz.16.9 oz.23.7 oz.33.8 oz.50.7 oz.mL330 mL500 mL700 mL1000 mL1500 mLStandard Pack Sizes6, 366, 246, 126, 1212"}"""
        }
    ]
)

print(completion.choices[0].message)
