from dotenv import load_dotenv
from openai import OpenAI
import os

# Setup for OpenAI
load_dotenv()
api_key = os.getenv("OPENAI_API_KEY")
client = OpenAI(api_key=api_key)

# Prompt OpenAi
completion = client.chat.completions.create(
    model="gpt-3.5-turbo",
    messages=[
        {"role": "system",
        "content": "Given the scraped data from Amazon, provide a detailed and well-organized breakdown of its environmental impact factors in a table format. Avoid mentioning that there is limited data provided. Put N/A if information is existing or very limiting. Ensure the response is structured and formatted for clarity."
        },
        {"role": "user", 
        #  "content": """{'productTitle': 'Neineiwu Women Dressy Casual V-Neck T-Shirts Loose Puff Short-Sleeve Tops Tunic Blouse', 'productFactsDesktopExpander': 'Product detailsFabric type95% Rayon, 5% Spandex, Soft and Stretchable FabricCare instructionsMachine Wash or Hand WashOriginImportedClosure typePull OnCountry of OriginChinaAbout this itemSkin-Friendly Material. Women dressy casual short-sleeve blouse is soft, Lightweight, fit loose, not tight and falls nicely.Features: Classic V-neck and puff sleeve design, The short puff sleeve is feminine and cute. Good coverage on the upper arm. Great longer length to cover the the butt. A nicer dressy t-shirt.Matching: V-neck women t-shirts nice for dressing up or down,the V is perfect for stacking necklaces. Just long enough to wear with leggings and flattering either casual or dressy. You can also pair it with casual skirts, jeans, shorts, boots, cardigans, jacket, coat etc.Occasion: Puff short-sleeve tops for women is greats for work, beach, office, travel, holiday, picnic, vacation, party, club and dating. Fashion T-Shirts Tops Tunic Blouse for women fashion 2023. Suit for summer, spring and fall.Size&Garment Care: US SIZE: S=(US 4-6), M=(US 8-10), L=(US 12-14), XL=(US 16-18), 2XL=(US 18-20). Machine or Hand Wash with cold water. Do not tumble dry.See moreAbout this item', 'important-information': 'Important informationTo report an issue with this product or seller,click here.', 'aplus': "From the brandWelcome to Neineiwu!!!You can find some Casual&Dressy tops and blouses for women fashion in here! Neineiwu can provide options for your everyday wardrobe.Previous pageWomens Wops Dressy CasualVisit the StoreBlouses & Button-down shirtsVisit the StoreHow did we get our start?Neineiwu was founded in 2018, a company that specializes in the design and production of women's fashion.What makes our products unique?Neineiwu always try to provide new trendy and high quality womens tops. We are eager to design popular and unique clothing. We are committed to provide best shopping experience to our customers.What problem are we solving?Let women show their beauty through different clothesLet women have more choice and style display in dressing,The purpose is to make women more attractive and enjoy life better.Next page"} """
         "content": """{'productTitle': 'Teenage Mutant Ninja Turtles: Mutant Mayhem 4.5” Leonardo Basic Action Figure by Playmates Toys', 'feature-bullets': 'AUTHENTIC: Leo stands 4.5" tall and is highly detailed with individual sculpting and decoration to match his movie character.HIGHLY POSEABLE: Leo has 12 points of articulation for great, action-packed battle poses!ACCESSORIES: Leo comes ready for battle with his iconic twin katana, a separate weapons rack with different accessories, and a baby turtle!MOVIE PACKAGING: Leo comes in a highly decorated blister card package with bright, bold details that includes TMNT Mutant Mayhem movie branding.COLLECT THEM ALL: Collect all the TMNT Mutant Mayhem action figures and accessories from Playmates Toys, your Teenage Mutant Ninja Turtles Toy Headquarters!', 'productDetails_detailBullets_sections1': 'Product Dimensions7.5 x 2.25 x 4.5 inchesItem Weight3.88 ouncesCountry of OriginChinaASINB0BKH84VDBItem model number83281Manufacturer recommended age4 years and upBest Sellers Rank#52 in Toys & Games (See Top 100 in Toys & Games)#1 inAction FiguresCustomer Reviews4.84.8 out of 5 stars2,425 ratings4.8 out of 5 starsRelease dateJune 25, 2023LanguageEnglishManufacturerPlaymates Toys', 'productDescription': 'Get ready for the Mutant Mayhem figures and accessories, based on the new CG animated Teenage Mutant Ninja Turtles movie! Leonardo is the Turtles’ leader in blue, and now he’s a wannabe student in high school! As Leo and his brothers start to leave the nest—er, the sewer—he’s set on transforming them into a crime-fighting team that he can lead to victory. With some help from their rat-dad Splinter, the Teenage Mutant Ninja Turtles will be undefeetable! (Foot pun intended). Leonardo figure is 4.5” tall and designed to match his movie character. Set includes his signature katana and comes in a unique Mutant Mayhem package!', 'important-information': 'Important informationSafety InformationChoking Hazard: Contains Small PartsTo report an issue with this product or seller,click here.', 'aplus': 'From the manufacturerGet ready for the Mutant Mayhem figures and accessories, based on the new CG animated Teenage Mutant Ninja Turtles movie! Leonardo is the Turtles’ leader in blue, and now he’s a hopeful student in high school! As 
Leo and his brothers start to leave the nest—er, the sewer—he’s set on transforming them into a crime-fighting team that he can lead to victory. With some help from their rat-dad Splinter, the Teenage Mutant Ninja Turtles will be unstoppable! Leonardo figure is 4.5” tall and designed to match his movie character. Set includes his signature katana and comes in a unique Mutant Mayhem package!HIGHLY POSEABLE: Leo has 12 points ofarticulation for great, action-packedbattle poses!WEAPONS HOLSTER: Leo carries his twinkatana in holsters on his back shell thatare ready for battle if needed.ACCESSORIES: Leo comes ready forbattle with his iconic twin katana, aseparate weapons rack with differentaccessories, and a baby turtle!'}"""
        }
    ]
)

print(completion.choices[0].message)
